Repository MegafonWebLab/megafon-ui, pull requests merged in 2022-05, with the labels that each got.

#929 Extra small button size
  packages/ui-core/src/components/Button/Button.less
  packages/ui-core/src/components/Button/Button.test.tsx
  packages/ui-core/src/components/Button/Button.tsx
  packages/ui-core/src/components/Button/__snapshots__/Button.test.tsx.snap
  packages/ui-core/src/components/Button/doc/Button.example.mdx
Labels: waiting release

#928 fix(logo): fix horizontal logo svg
  packages/ui-core/src/components/Logo/green-horizontal.svg
Labels: waiting release

#934 feat(notification): add props classes to notification component
  packages/ui-core/src/components/Notification/Notification.test.tsx
  packages/ui-core/src/components/Notification/Notification.tsx
  packages/ui-core/src/components/Notification/__snapshots__/Notification.test.tsx.snap
Labels: waiting release

#905 fix(breadcrumbs): change default color prop value from black to default
  packages/ui-shared/src/components/Breadcrumbs/Breadcrumbs.tsx
  packages/ui-shared/src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
Labels: waiting release, beta

#938 fix(instructions): remove css prorerty filter for image
  packages/ui-shared/src/components/Instructions/Instructions.less
  packages/ui-shared/src/components/Instructions/Instructions.tsx
  packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
Labels: waiting release

#937 fix(picturewithdescription): fix clearing indents for first and last …
  packages/ui-shared/src/components/PictureWithDescription/PictureWithDescription.less
Labels: waiting release

#941 fix(select): fix selected item color when value is zero
  packages/ui-core/src/components/Select/Select.tsx
  packages/ui-core/src/components/Select/doc/Select.docz.tsx
  packages/ui-core/src/components/Select/doc/Select.example.mdx
Labels: waiting release

#946 feat(tooltip): add portal selector props
  packages/ui-core/src/components/Tooltip/Tooltip.tsx
  packages/ui-core/src/components/Tooltip/doc/Tooltip.example.mdx
Labels: waiting release

#944 feat(switcher): add data-attribute for inner element
  packages/ui-core/src/components/Switcher/Switcher.test.tsx
  packages/ui-core/src/components/Switcher/Switcher.tsx
  packages/ui-core/src/components/Switcher/__snapshots__/Switcher.test.tsx.snap
Labels: waiting release

#939 feat(accordion): update by new design
  packages/ui-core/src/colors/Colors.less
  packages/ui-core/src/components/Accordion/Accordion.less
  packages/ui-core/src/components/Accordion/Accordion.test.tsx
  packages/ui-core/src/components/Accordion/Accordion.tsx
  packages/ui-core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
  packages/ui-core/src/components/Accordion/doc/Accordion.example.mdx
  packages/ui-core/src/components/Switcher/Switcher.less
  packages/ui-core/src/components/Tabs/Tabs.less
  packages/ui-core/src/components/Tooltip/Tooltip.less
  packages/ui-core/src/styles/base.less
Labels: beta

#948 feat(instructions): add swipe to picture
  packages/ui-shared/src/components/Instructions/Instructions.tsx
  packages/ui-shared/src/components/Instructions/__snapshots__/Instructions.test.tsx.snap
Labels: waiting release

#942 feat(banner): add new prop 'pauseOnHover'
  packages/ui-core/src/components/Banner/Banner.tsx
  packages/ui-core/src/components/Banner/__snapshots__/Banner.test.tsx.snap
  packages/ui-core/src/components/Banner/doc/Banner.example.mdx
Labels: waiting release
